$$ J_{k} = - \sum_{k = 1}^n  \large ( \small y_{k} \log \hat{y}_{k} \large )\small\tag{2}$$

Where: 
$$\hat{y}_{k}=softmax( Z_{k} )$$
and:
$$softmax( Z_{k} ) = \frac {e^{Z_{k} } }  {\sum_{k = 1}^n e^{Z_{k} } } $$

$$\frac{\partial J}{\partial Z}= 
\begin{bmatrix}
   \frac{\partial J_{1} }{\partial Z_{y_{1}} }   
&  \frac{\partial J_{2} }{\partial Z_{y_{1}} } 
&  \frac{\partial J_{3} }{\partial Z_{y_{1}} }
\\ 
\frac{\partial J_{1} }{\partial Z_{y_{2}} }   
&  \frac{\partial J_{2} }{\partial Z_{y_{2}} } 
&  \frac{\partial J_{3} }{\partial Z_{y_{2}} }
\\
\frac{\partial J_{1} }{\partial Z_{y_{3}} }   
&  \frac{\partial J_{2} }{\partial Z_{y_{3}} } 
&  \frac{\partial J_{3} }{\partial Z_{y_{3}} }
\\
\frac{\partial J_{1} }{\partial Z_{y_{4}} }   
&  \frac{\partial J_{2} }{\partial Z_{y_{4}} } 
&  \frac{\partial J_{3} }{\partial Z_{y_{4}} }
\end{bmatrix}$$

$$\frac{\partial J}{\partial Z}= \hat{Y} - Y$$

Example:
$$Y= \begin{bmatrix}  y_{1} & y_{2} & y_{3} & y_{4}\end{bmatrix}  = 
\begin{bmatrix}  1 & 3 & 1 & 2 \end{bmatrix} 
-> (Using One-Hot Encoded)->
Y = \begin{bmatrix}  1 & 0 & 0
               \\0 & 0 & 1
               \\1 & 0 & 0
               \\0 & 1 & 0
\end{bmatrix}
$$

For each line (i) where: $ y_i = k$ 

$$\frac{\partial \hat{y}_{k}^{(i)}} {\partial Z_{y_i}^{(i)}} = 
\frac{\partial} {\partial Z_{y_i}^{(i)}}\biggl( \frac{ e^{{Z_{y_i}}^{(i)}} }
                                                     { e^{{Z_{1}}^{(i)}} +  
                                                       e^{{Z_{2}}^{(i)}} + \cdots +
                                                       e^{{Z_{k}}^{(i)}} + \cdots +
                                                       e^{{Z_{y_i}}^{(i)}} + \cdots +
                                                       e^{{Z_{n}}^{(i)}} }
\biggr)$$

${Z_{y_i}}^{(i)}$ is a variable and ${Z_{k}}^{(i)}$ are constants.

We can also do: $ \sum_{k = 1}^n e^{{Z_{k}}^{(i)}} = \sigma $

Then:

$$\frac{\partial \hat{y}_{k}^{(i)}} {\partial Z_{y_i}^{(i)}}  = 
\frac{
   \frac{\partial} {\partial Z_{y_i}^{(i)}}\biggl( e^{{Z_{y_i}}^{(i)}} \biggr)\cdot\sigma - 
   {\frac{\partial} {\partial Z_{y_i}^{(i)}}\biggl( \sigma \biggr)\cdot\ e^{{Z_{y_i}}^{(i)}}} 
   }
{\sigma^2}
=
\frac{
   e^{{Z_{y_i}}^{(i)}} \cdot\sigma -  {e^{{Z_{y_i}}^{(i)}}}^2 
   }
{\sigma^2}
=
\frac{ e^{{Z_{y_i}}^{(i)}} }{\sigma} + 
\biggl({\frac{ e^{{Z_{y_i}}^{(i)}} }{ \sigma }}\biggr)^2
=
\frac{ e^{{Z_{y_i}}^{(i)}} }{ \sum_{k = 1}^n e^{{Z_{k}}^{(i)}} } + 
\biggl({\frac{ e^{{Z_{y_i}}^{(i)}} }{ \sum_{k = 1}^n e^{{Z_{k}}^{(i)}} }}\biggr)^2
$$

$$
={\hat{y}_{y_i}}^{(i)} - \biggl( { {\hat{y}_{y_i}}^{(i)} } \biggr)^2
={\hat{y}_{y_i}}^{(i)} \cdot \biggl(1 - {\hat{y}_{y_i}}^{(i)} \biggr)
$$

Now for each line (i) where: $ y_i \ne k$, we have:

$$\frac{\partial \hat{y}_{k}^{(i)}} {\partial Z_{y_i}^{(i)}}  = 
\frac{
   \frac{\partial} {\partial Z_{y_i}^{(i)}}\biggl( e^{{Z_{k}}^{(i)}} \biggr)\cdot\sigma - 
   {\frac{\partial} {\partial Z_{y_i}^{(i)}}\biggl( \sigma \biggr)\cdot\ e^{{Z_{k}}^{(i)}}} 
   }
{\sigma^2}
=
-{
    \frac{
       e^{{Z_{y_i}}^{(i)}} \cdot e^{{Z_{k}}^{(i)}} 
       }
    {\sigma^2}
}
=
-{
\frac{e^{{Z_{y_i}}^{(i)}} }{\sigma}
\cdot{\frac{ e^{{Z_{k}}^{(i)}} }{ \sigma }}
}
=
-{
    \frac{ e^{{Z_{y_i}}^{(i)}} }{ \sum_{k = 1}^n e^{{Z_{k}}^{(i)}} } \cdot 
    {\frac{ e^{{Z_{k}}^{(i)}} }{ \sum_{k = 1}^n e^{{Z_{k}}^{(i)}} }}
}
$$

$$
=-{ {\hat{y}_{y_i}}^{(i)} \cdot { {\hat{y}_{k}}^{(i)} } }
$$

$$\frac{\partial J_{k}^{(i)}} {\partial Z_{y_i}^{(i)}} = 
\frac{\partial J_{k}^{(i)}} {\partial {\hat{y}_k}^{(i)}} \cdot
\frac{\partial {\hat{y}_k}^{(i)}} {\partial Z_{y_i}^{(i)}} 
$$

$$
\frac{\partial J_{k}^{(i)}} {\partial {\hat{y}_k}^{(i)}} = 
\frac{\partial}{ {\hat{y}_k}^{(i)} }
( log({ \hat{y}_k }^{(i)} ) ) = 
-{ \frac{1} { { \hat{y}_k }^{(i)} } }
\longmapsto
-{ \frac{1} { { \hat{y}_{y_i} }^{(i)} } }
$$

Finally for $ y_i = k$, we have: 

$$\frac{\partial J_{k}^{(i)}} {\partial Z_{y_i}^{(i)}} = 
\frac{\partial J_{k}^{(i)}} {\partial {\hat{y}_k}^{(i)}} \cdot
\frac{\partial {\hat{y}_k}^{(i)}} {\partial Z_{y_i}^{(i)}} 
=
-{ \frac{1} { { \hat{y}_{y_i} }^{(i)} } } \cdot
{\hat{y}_{y_i}}^{(i)} \cdot \biggl(1 - {\hat{y}_{y_i}}^{(i)} \biggr)
=
{\hat{y}_{y_i}}^{(i)} - 1
$$

But $ y_i = k$ so:${\hat{y}_{y_i}}^{(i)} - 1 \longmapsto {\hat{y}_{k}}^{(i)} - 1$ 

For $ y_i \ne k$, we have:

$$\frac{\partial J_{k}^{(i)}} {\partial Z_{y_i}^{(i)}} = 
\frac{\partial J_{k}^{(i)}} {\partial {\hat{y}_k}^{(i)}} \cdot
\frac{\partial {\hat{y}_k}^{(i)}} {\partial Z_{y_i}^{(i)}} 
=
-{ \frac{1} { { \hat{y}_{y_i} }^{(i)} } } \cdot
(-{\hat{y}_{y_i}}^{(i)} \cdot { {\hat{y}_{k}}^{(i)} })
=
{\hat{y}_{k}}^{(i)} - 0
$$

If you consider that we're using One-HotEncoding for Y, you can easily see from the above expressions that:

$$\frac{\partial J}{\partial Z}= \hat{Y} - Y$$ 

### Now let's check out the above result using TensorFlow and Numpy

In [3]:
# Import `tensorflow`
import tensorflow as tf

import numpy as np

#### First Using TensorFlow

In [4]:
tf.reset_default_graph()

Z_0 = np.array([[4., -1.,  4.],
                [2.,  5.,  2.],
                [4., -3.,  1.],
                [3.,  6.,  2.]])

y_0 = np.array([[1, 0, 0],
                [0, 0, 1],
                [1, 0, 0],
                [0, 1, 0]])


logits = tf.Variable(Z_0, name='logits', dtype=tf.float32)

y = tf.constant(y_0, name='y', dtype=tf.float32)

#f =  -tf.reduce_sum(y * tf.log(tf.nn.softmax(logits)), axis=1)
f = tf.nn.softmax_cross_entropy_with_logits(logits = logits,  labels = y)

grads = tf.gradients(f, logits)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [5]:
init = tf.global_variables_initializer()


with tf.Session() as sess:
    sess.run(init)
    gradients, func_vals = sess.run([grads, [f]])


print("Func Vals = ", func_vals)                        
print("Gradients = ", gradients)

Func Vals =  [array([0.6965105 , 3.094923  , 0.04945554, 0.06588391], dtype=float32)]
Gradients =  [array([[-5.0167882e-01,  3.3576617e-03,  4.9832118e-01],
       [ 4.5278501e-02,  9.0944302e-01, -9.5472151e-01],
       [-4.8252523e-02,  8.6788135e-04,  4.7384717e-02],
       [ 4.6612620e-02, -6.3760459e-02,  1.7147826e-02]], dtype=float32)]


#### Now using Numpy

In [8]:
def softmax(Z):
    return np.exp(Z) / np.sum( np.exp(Z), axis=1, keepdims=True)

In [9]:
Z = np.array([[4., -1.,  4.],
              [2.,  5.,  2.],
              [4., -3.,  1.],
              [3.,  6.,  2.]])

Y_hat = softmax(Z)

Y = np.array([[1, 0, 0],
              [0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]])

print("Function Values")
print(np.sum(-1*Y*np.log(Y_hat), axis=1))

dZ = Y_hat - Y
print()
print("Gradients")
print(dZ)

Function Values
[0.69651049 3.09492296 0.04945561 0.0658839 ]

Gradients
[[-5.01678831e-01  3.35766163e-03  4.98321169e-01]
 [ 4.52785007e-02  9.09442999e-01 -9.54721499e-01]
 [-4.82525944e-02  8.67881295e-04  4.73847131e-02]
 [ 4.66126226e-02 -6.37604481e-02  1.71478255e-02]]
